name: ci

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Install iOS workload
        run: dotnet workload install ios

      - name: Build package project
        run: |
          dotnet build src/Kapusch.StoreKit2ApisForiOSComponents/Kapusch.StoreKit2ApisForiOSComponents.csproj -c Release
